### ISSUE TITLE
Include engines giving me error and also not able to run command ./gradlew test

### ISSUE THREAD

**Issue by onlyAnkita** [98elements/calculator#1]
test {
    useJUnitPlatform {
        includeEngines 'spek2'
    }

putting the above code in build.gradle is giving me the error of 
 
Could not find method test() for arguments [build_2z0c36mbbiuu9kdkv7muthi3e$_run_closure1@4183a6bb] on root project 'SpekAndroid' of type org.gradle.api.Project.
Open File

**Comment by tomekw** [comment]
Hello @Ankita1405. Interesting... Could you post more details? Does it work when you just clone the repo and run `./gradlew test`? I presume you have copied some bits from the `build.gradle` in the repo...
